lib/surveyor_web/router.ex
defmodule SurveyorWeb.Router do
  use SurveyorWeb, :router

  import SurveyorWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SurveyorWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SurveyorWeb do
    pipe_through :browser

    live "/", HomePageLive, :index
    get "/vote/:survey_name", VoteController, :index
    post "/vote/:survey_name/", VoteController, :cast_vote
    live "/chart/:survey_name", VoteGraphLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SurveyorWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SurveyorWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", SurveyorWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SurveyorWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/surveys", SurveyLive.Index, :index
    live "/surveys/new", SurveyLive.Index, :new
    live "/surveys/:id/edit", SurveyLive.Index, :edit

    live "/surveys/:id", SurveyLive.Show, :show
    live "/surveys/:id/show/edit", SurveyLive.Show, :edit
  end

  scope "/", SurveyorWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/surveyor_web/live/home_page_live.ex
defmodule SurveyorWeb.HomePageLive do
  use SurveyorWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :surveys, list_surveys())}
  end

  defp list_surveys do
    Surveyor.Surveys.list_surveys()
  end
end

lib/surveyor_web/live/live_helpers.ex
defmodule SurveyorWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `SurveyorWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, SurveyorWeb.SurveyLive.FormComponent,
        id: @survey.id || :new,
        action: @live_action,
        survey: @survey,
        return_to: Routes.survey_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, SurveyorWeb.ModalComponent, modal_opts)
  end
end

lib/surveyor_web/live/modal_component.ex
defmodule SurveyorWeb.ModalComponent do
  use SurveyorWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/surveyor_web/live/page_live.ex
defmodule SurveyorWeb.PageLive do
  use SurveyorWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :surveys, list_surveys())}
  end

  defp list_surveys do
    Surveyor.Surveys.list_surveys()
  end
end

lib/surveyor_web/live/survey_live/form_component.ex
defmodule SurveyorWeb.SurveyLive.FormComponent do
  use SurveyorWeb, :live_component

  alias Surveyor.Surveys

  @impl true
  def update(%{survey: survey} = assigns, socket) do
    changeset = Surveys.change_survey(survey)
    options = case assigns.action do
      :edit ->
        assigns.survey.options
        |> Map.keys()
      :new ->
        []
    end

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)
     |> assign(:current_option, "")
     |> assign(:options, options)}
  end

  @impl true
  def handle_event("delete-option", %{"index" => index}, socket) do
    options = List.delete_at(socket.assigns.options, String.to_integer(index))
    {:noreply,
      socket
      |> assign(:options, options)}
  end

  @impl true
  def handle_event("add-current-option", _params, socket) do
    options =
      case socket.assigns.current_option do
        "" ->
         socket.assigns.options
       current_option ->
         [current_option | socket.assigns.options]
      end

    {:noreply,
      socket
      |> push_event("clear-input", %{})
      |> assign(:current_option, "")
      |> assign(:options, options)}
  end


  @impl true
  def handle_event("validate", %{"survey" => survey_params = %{"option" => current_option}}, socket) do
    changeset =
      socket.assigns.survey
      |> Surveys.change_survey(survey_params)
      |> Map.put(:action, :validate)

    {:noreply,
      socket
      |> assign(:current_option, current_option)
      |> assign(:changeset, changeset)}
  end

  def handle_event("save", %{"survey" => survey_params}, socket) do
    survey_params =
      survey_params
      |> Map.put("options",
        socket.assigns.options
        |> Enum.map(fn x -> {x, 0} end)
        |> Enum.into(%{}))
      |> Map.put("user_id", socket.assigns.user_id)
    IO.inspect(survey_params)
    save_survey(socket, socket.assigns.action, survey_params)
  end

  defp save_survey(socket, :edit, survey_params) do
    survey_params = Map.put(survey_params, "options",
      socket.assigns.options
      |> Enum.map(fn x -> {x, 0} end)
      |> Enum.into(%{})
    )

    case Surveys.update_survey(socket.assigns.survey, survey_params) do
      {:ok, _survey} ->
        {:noreply,
         socket
         |> put_flash(:info, "Survey updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_survey(socket, :new, survey_params) do
    user = Surveyor.Accounts.get_user!(survey_params["user_id"])
    case Surveys.create_survey(user, survey_params) do
      {:ok, _survey} ->
        {:noreply,
         socket
         |> put_flash(:info, "Survey created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/surveyor_web/live/survey_live/index.ex
defmodule SurveyorWeb.SurveyLive.Index do
  use SurveyorWeb, :live_view

  alias Surveyor.Surveys
  alias Surveyor.Surveys.Survey
  alias Surveyor.Accounts

  @impl true
  def mount(_params, %{"user_token" => user_token}, socket) do
    user = Accounts.get_user_by_session_token(user_token)
    {:ok,
      socket
      |> assign(:user_id, user.id)
      |> assign(:surveys, list_surveys(user.id))}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Survey")
    |> assign(:survey, Surveys.get_survey!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Survey")
    |> assign(:survey, %Survey{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Surveys")
    |> assign(:survey, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    survey = Surveys.get_survey!(id)
    {:ok, _} = Surveys.delete_survey(survey)

    {:noreply, assign(socket, :surveys, list_surveys(socket.assigns.user_id))}
  end

  defp list_surveys(user_id) do
    Surveys.list_surveys_by_user_id(user_id)
  end
end

lib/surveyor_web/live/survey_live/show.ex
defmodule SurveyorWeb.SurveyLive.Show do
  use SurveyorWeb, :live_view

  alias Surveyor.Surveys

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:survey, Surveys.get_survey!(id))}
  end

  defp page_title(:show), do: "Show Survey"
  defp page_title(:edit), do: "Edit Survey"
end

lib/surveyor_web/live/vote_graph_live.ex
defmodule SurveyorWeb.VoteGraphLive do
  use SurveyorWeb, :live_view

  alias Surveyor.Surveys

  @impl true
  def mount(_params, session, socket) do
    {:ok, assign(socket, :session, session)}
  end

  @impl true
  def handle_params(%{"survey_name" => survey_name}, _, socket) do
    case show_chart?(socket.assigns.session, survey_name) do
      true ->
        survey = Surveys.get_survey_by_name!(survey_name)
        {:noreply,
           socket
           |> push_event("chart-data", %{label: survey.name ,data: survey.options})
           |> assign(:survey, survey)}
      false ->
        {:noreply, redirect(socket, to: Routes.home_page_path(socket, :index))}
    end
  end

  def show_chart?(session, survey_name) do
    case has_voting_session?(session) do
      false ->
        false
      true ->
        voted_on_survey?(session, survey_name)
    end
  end

  def has_voting_session?(session) do
    Map.has_key?(session, "voting_session")
  end

  def voted_on_survey?(%{"voting_session" => voting_session}, survey_name) do
    Map.has_key?(voting_session, survey_name)
  end

end

lib/surveyor_web/live/survey_live/form_component.html.leex
<h2 class="text-xl font-bold text-center"><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "survey-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save",
  onkeydown: "return event.key != 'Enter';"%>

  <%= label f, :name, class: "input-text" %>
  <%= text_input f, :name, class: "input-area" %>
  <%= error_tag f, :name %>

  <%= label f, :question, class: "input-text" %>
  <%= text_input f, :question, class: "input-area" %>
  <%= error_tag f, :question %>

  <%= label f, :options, class: "input-text" %>

  <ul>
  <%= for {option, index} <- Enum.with_index(@options) do %>
    <li>
    <div class="m-2 flex flex-row justify-around rounded shadow bg-gray-50 p-2">
      <%= option %>
      <div phx-click="delete-option" phx-target="<%= @myself %>" phx-value-index="<%= index %>">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      </div>
    </div>
    </li>
  <% end %>
  </ul>

  <%= text_input f, :option, class: "input-area", value: @current_option, phx_target: @myself, phx_hook: "optionTextInput", phx_keydown: "add-current-option", phx_key: "Enter" %>

  <button phx-click="add-current-option" phx-target="<%= @myself %>" type="button">Add Option</button>

  <%= submit "Save", phx_disable_with: "Saving..." %>
</form>

lib/surveyor_web/live/survey_live/index.html.leex
<h1 class="text-xl font-bold text-center">My Surveys</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, SurveyorWeb.SurveyLive.FormComponent,
    id: @survey.id || :new,
    title: @page_title,
    action: @live_action,
    survey: @survey,
    user_id: @user_id,
    return_to: Routes.survey_index_path(@socket, :index) %>
<% end %>

    <%= for survey <- @surveys do %>
      <div class="mt-2 flex flex-row justify-around bg-gray-50 shadow rounded p-4">
        <h3><%= survey.name %></h3>

        <div>
          <span><%= live_redirect "View", to: Routes.survey_show_path(@socket, :show, survey) %></span>
          <span><%= live_patch "Edit", to: Routes.survey_index_path(@socket, :edit, survey) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: survey.id, data: [confirm: "Are you sure?"] %></span>
        </div>
      </div>
    <% end %>
<div class="mt-2 flex flex-row justify-center">
  <span><%= live_patch "New Survey", to: Routes.survey_index_path(@socket, :new) %></span>
</div>

lib/surveyor_web/live/survey_live/show.html.leex
<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, SurveyorWeb.SurveyLive.FormComponent,
    id: @survey.id,
    title: @page_title,
    action: @live_action,
    survey: @survey,
    return_to: Routes.survey_show_path(@socket, :show, @survey) %>
<% end %>

  <div class="flex flex-col bg-gray-50 rounded shadow p-4">
    <div class="flex flex-row justify-start">
      <strong>Name:</strong>
      <%= @survey.name %>
    </div>

    <div class="flex flex-row justify-start">
      <strong>Question:</strong>
      <%= @survey.question %>
    </div>

    <div class="flex flex-row justify-start">
      <strong>Options:</strong>
      <ul>
        <%= for {key, value} <- @survey.options do %>
          <li>
            <%= key %> : <%= value %>
          </li>
        <% end%>
      </ul>
    </div>
  </div>


<span><%= live_patch "Edit", to: Routes.survey_show_path(@socket, :edit, @survey), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.survey_index_path(@socket, :index) %></span>